### ISSUE TITLE
Improve the inventory workflow

### ISSUE THREAD

**Issue by HiranChaudhuri** [grocy/docs#15]
Reading https://github.com/grocy/docs/blob/master/tutorials/food.md#inventory it seems inventory just consists of putting new amounts for existing products. The reality is different, especially when your storage location is not online. In this case you probably want to print grocy's version of stock, take that to the location. Searching every product and correcting the numbers on the sheet, you come back online and enter the numbers you got.

In this case it is extremely useful to have a good sheet with goods to look for. Which one is the best to be printed?

**Comment by kses** [comment]
The inventory feature is a stock take feature. As most features in the web-ui it is primarily intended to be used together with a laser scanner.

It is not intended to be printed. The intention of grocy is to have a connection to your server where you interact with the thing you track. You do not need to be online, but connected to your grocy server. This feature do not seem to match what you want to do.

If you want to print current stock, you can do that via the stock overview screen. Stock overview>location content screen>print "this" location OR print all locations.

**Comment by kses** [comment]
If you have a working workflow for offline data that you want to share, then we can add it to the documentation.

As far as I know there is no real support for the workflow that you are suggesting. If I have missed it please tell me how and I will add it.
